[phases.setup]
nixPkgs = ["python311", "gcc"] # Cambia a python310 si prefieres esa

[phases.install]
cmds = ["python -m venv /app/.venv", ". /app/.venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /app/.venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8000"